name: Generate ascii artwork

on: 
 push

jobs:
 ascii_job:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v4
     
     - name: Install cowsay pgm
       run: sudo apt-get install -y cowsay

     - name: Execute cowsay cmd
       run: cowsay -f dragon "Run for cover, run for fun!" >> dragon.txt

     - name: check file exists
       run: grep -i "dragon" dragon.txt

     - name: read file
       run: cat dragon.txt

     - name: list repo files
       run: ls -ltra