name: Generate ascii artwork

on: 
 push

jobs:
 ascii_job:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v4

     - name: List files
       run: ls -ltra  
     
     - name: Executing shell script
       run: ./ascii-script.sh