name: My workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            
          - name: list and read files
            run: |
              echo "My first Github Actions Job"
              ls -ltr
              cat README.md
          
          - name: Generate ASCII Artwork
            run: cowsay -f dragon "Run for cover, run for fun!" >> dragon.txt