name: Matrix configuration

on:
 push:
 workflow_dispatch:

jobs:
   deploy-on-ubuntu:
    strategy:
        matrix:
           os: [ubuntu-latest, ubuntu-22.04, windwows-latest]
           images: [hello-world, alpine]
    runs-on: ${{ matrix.os}}
    steps:
      - name: Echo Docker details
        run: docker info
      
      - name: run images on ${{ matrix.images }}
        run: docker run ${{ matrix.images}}